#!/bin/bash

# Genreate the qm file used by the translator
lrelease libmesact/eng-de.ts libmesact/eng-de.qm
lrelease libmesact/eng-es.ts libmesact/eng-es.qm
lrelease libmesact/eng-fr.ts libmesact/eng-fr.qm
